@echo off
echo Starting Legal Chatbot...
echo Ensuring dependencies are installed...
pip install -r requirements.txt
echo Please ensure Ollama is running (run 'ollama serve' or open the app).
echo Starting Server...
cd app\project-01
python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000
